steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gentle-cable-418618/flask-app:latest', '.']
  dir: 'flask-app'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gentle-cable-418618/flask-app:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'reset', 'flask-app-instance', '--zone', 'us-central1-a']

