steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/apt-cycling-418613/ci-assign2/flask-img:latest', '.']
  dir: 'flask-app'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/apt-cycling-418613/ci-assign2/flask-img:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'reset', 'flask-app-instance', '--zone', 'northamerica-northeast1-a']

